# Generated by Django 4.2.9 on 2024-02-11 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False, help_text='Поставьте галочку, чтобы  опубликовать.', verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('category_service_name', models.CharField(choices=[('BUILDING', 'BUILDING'), ('HOME_DEALS', 'HOME_DEALS'), ('TEACHING', 'TEACHING'), ('RENTING', 'RENTING'), ('OTHER', 'OTHER')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False, help_text='Поставьте галочку, чтобы  опубликовать.', verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('service_name', models.CharField(max_length=120)),
                ('service_description', models.TextField(blank=True, max_length=500, null=True)),
                ('service_cost', models.IntegerField(default=0)),
                ('service_category', models.ForeignKey(on_delete=django.db.models.deletion.SET, related_name='services', to='services.servicecategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
