# Generated by Django 4.2.9 on 2024-04-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='reason_for_not_publish',
            field=models.CharField(choices=[(1, 'Нарушает правило сайта'), (2, 'Не соответствует действительности')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='reason_for_not_publish',
            field=models.CharField(choices=[(1, 'Нарушает правило сайта'), (2, 'Не соответствует действительности')], max_length=100, null=True),
        ),
    ]
