# Generated by Django 4.2.9 on 2024-04-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_servicecategory_reason_for_not_publish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='reason_for_not_publish',
            field=models.CharField(blank=True, choices=[('Нарушает правило сайта', 'Нарушает правило сайта'), ('Не соответствует действительности', 'Не соответствует действительности'), ('Ненормативная лексика', 'Ненормативная лексика'), ('Другая причина', 'Другая причина')], default=False, max_length=100, null=True, verbose_name='Причина непубликации'),
        ),
        migrations.AlterField(
            model_name='services',
            name='reason_for_not_publish',
            field=models.CharField(blank=True, choices=[('Нарушает правило сайта', 'Нарушает правило сайта'), ('Не соответствует действительности', 'Не соответствует действительности'), ('Ненормативная лексика', 'Ненормативная лексика'), ('Другая причина', 'Другая причина')], default=False, max_length=100, null=True, verbose_name='Причина непубликации'),
        ),
    ]
