version: '3.3'

volumes:
  backend_static:
  media:
  pg_data:
services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - ../table/.env
    volumes:
      - pg_data:/var/lib/postgresql/data/
  redis:
    restart: always
    container_name: redis
    image: redis:7.0.5-alpine 
    expose:
        - 6379
  web:
    build: ../table/
    container_name: web
    command: gunicorn --bind 0.0.0.0:8000 table.wsgi
    env_file:
      - ../table/.env
    environment:
      - LOCATION=redis://redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - backend_static:/app/static/
      - media:/app/media/
  celery:
    build: ../table/
    container_name: celery
    command: celery -A table worker --loglevel=info -P eventlet
    env_file:
      - ../table/.env
    environment:
      - LOCATION=redis://redis:6379
    depends_on:
      - web
      - beat
  beat:
    build: ../table/
    container_name: beat
    command: celery -A table beat 
    env_file:
      - ../table/.env
    environment:
      - LOCATION=redis://redis:6379
    depends_on:
      - web
  flower:
    container_name: flower
    build: ../table/
    command: celery -A table flower
    ports:
    - 5555:5555
    env_file:
      - ../table/.env
    environment:
      - LOCATION=redis://redis:6379
    depends_on:
      - celery
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - backend_static:/app/static/
      - media:/media/

      # python manage.py migrate
      # python manage.py collectstatic
      # cp -r /collected_static/. /app/static/