# Generated by Django 4.2.9 on 2024-04-16 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(verbose_name='кол-во товара')),
            ],
            options={
                'verbose_name': 'список покупок',
                'verbose_name_plural': 'список покупок',
                'default_related_name': 'carts',
            },
        ),
        migrations.CreateModel(
            name='GoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False, help_text='Поставьте галочку, чтобы  опубликовать.', verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('reason_for_not_publish', models.CharField(blank=True, choices=[('Нарушает правило сайта', 'Нарушает правило сайта'), ('Не соответствует действительности', 'Не соответствует действительности'), ('Ненормативная лексика', 'Ненормативная лексика'), ('Другая причина', 'Другая причина')], default=False, max_length=100, null=True, verbose_name='Причина непубликации')),
                ('category_good_name', models.CharField(max_length=100, verbose_name='Наименование категории')),
                ('category_description', models.TextField(max_length=500, verbose_name='Описание группы товаров')),
                ('category_slug', models.SlugField(unique=True, verbose_name='Идентификатор категории')),
            ],
            options={
                'verbose_name': 'категория товаров',
                'verbose_name_plural': 'категории товаров',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False, help_text='Поставьте галочку, чтобы  опубликовать.', verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('reason_for_not_publish', models.CharField(blank=True, choices=[('Нарушает правило сайта', 'Нарушает правило сайта'), ('Не соответствует действительности', 'Не соответствует действительности'), ('Ненормативная лексика', 'Ненормативная лексика'), ('Другая причина', 'Другая причина')], default=False, max_length=100, null=True, verbose_name='Причина непубликации')),
                ('good_name', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель товара')),
                ('condition', models.CharField(choices=[('NEW', 'Новое'), ('USED', 'БУ')], max_length=5)),
                ('in_stock', models.BooleanField(default=False, verbose_name='в наличии')),
                ('good_cost', models.IntegerField(verbose_name='Стоимость товара')),
                ('description', models.TextField(max_length=500, verbose_name='Описание товара')),
                ('slug', models.SlugField(null=True, unique=True, verbose_name='Идентификатор')),
                ('good_category', models.ForeignKey(on_delete=django.db.models.deletion.SET, related_name='goods', to='goods.goodcategory', verbose_name='категория товара')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL, verbose_name='продавец')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='WishGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'желаемый товар',
                'verbose_name_plural': 'желаемые товары',
                'default_related_name': 'wishes',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=12, region='RU')),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('delivery_method', models.CharField(choices=[('Почта', 'Почта'), ('Курьер', 'Курьер')], max_length=6)),
                ('cart', models.ManyToManyField(related_name='cart', to='goods.carts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='GoodsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False, help_text='Поставьте галочку, чтобы  опубликовать.', verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('reason_for_not_publish', models.CharField(blank=True, choices=[('Нарушает правило сайта', 'Нарушает правило сайта'), ('Не соответствует действительности', 'Не соответствует действительности'), ('Ненормативная лексика', 'Ненормативная лексика'), ('Другая причина', 'Другая причина')], default=False, max_length=100, null=True, verbose_name='Причина непубликации')),
                ('good_photo', models.ImageField(blank=True, null=True, upload_to='media/goods/', verbose_name='Изображение товара')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.goods', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'Архив фото товаров',
            },
        ),
        migrations.AddField(
            model_name='carts',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='carts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
