# Generated by Django 4.2.9 on 2024-02-13 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='good_photo',
        ),
        migrations.CreateModel(
            name='GoodsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False, help_text='Поставьте галочку, чтобы  опубликовать.', verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('good_photo', models.ImageField(blank=True, upload_to='media/goods/', verbose_name='Изображение товара')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='goods.goods')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
