# Generated by Django 4.2.9 on 2024-02-13 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_remove_goods_good_photo_goodsphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsphoto',
            old_name='goods',
            new_name='good',
        ),
    ]
