# Generated by Django 4.2.9 on 2024-02-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_rename_goods_goodsphoto_good'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='slug',
            field=models.SlugField(help_text='Идентификатор страницы для URL; разрешены символы латиницы, цифры, дефис и подчёркивание.', null=True, unique=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='condition',
            field=models.CharField(choices=[('Новое', 'NEW'), ('БУ', 'USED')], max_length=5),
        ),
    ]
