# Generated by Django 4.2.9 on 2024-02-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_goods_slug_alter_goods_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Идентификатор'),
        ),
    ]
