# Generated by Django 4.2.9 on 2024-04-03 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0006_alter_goods_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstactUserGoodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='goods.goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('abstactusergoodmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goods.abstactusergoodmodel')),
                ('quantity', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'список покупок',
                'verbose_name_plural': 'список покупок',
                'default_related_name': 'carts',
            },
            bases=('goods.abstactusergoodmodel',),
        ),
        migrations.CreateModel(
            name='WishGoods',
            fields=[
                ('abstactusergoodmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='goods.abstactusergoodmodel')),
            ],
            options={
                'verbose_name': 'желаемый товар',
                'verbose_name_plural': 'желаемые товары',
                'default_related_name': 'wishes',
            },
            bases=('goods.abstactusergoodmodel',),
        ),
    ]
