# Generated by Django 4.2.9 on 2024-04-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_abstactusergoodmodel_carts_wishgoods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsphoto',
            name='good_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/goods/', verbose_name='Изображение товара'),
        ),
    ]
