# Generated by Django 4.2.9 on 2024-04-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_alter_goodsphoto_good_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodcategory',
            name='reason_for_not_publish',
            field=models.CharField(choices=[(1, 'Нарушает правило сайта'), (2, 'Не соответствует действительности')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goods',
            name='reason_for_not_publish',
            field=models.CharField(choices=[(1, 'Нарушает правило сайта'), (2, 'Не соответствует действительности')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='goodsphoto',
            name='reason_for_not_publish',
            field=models.CharField(choices=[(1, 'Нарушает правило сайта'), (2, 'Не соответствует действительности')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='condition',
            field=models.CharField(choices=[('NEW', 'Новое'), ('USED', 'БУ')], max_length=5),
        ),
    ]
