# Generated by Django 4.2.9 on 2024-04-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_goodcategory_reason_for_not_publish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodcategory',
            name='reason_for_not_publish',
            field=models.CharField(blank=True, choices=[('Нарушает правило сайта', 'Нарушает правило сайта'), ('Не соответствует действительности', 'Не соответствует действительности'), ('Ненормативная лексика', 'Ненормативная лексика'), ('Другая причина', 'Другая причина')], default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='reason_for_not_publish',
            field=models.CharField(blank=True, choices=[('Нарушает правило сайта', 'Нарушает правило сайта'), ('Не соответствует действительности', 'Не соответствует действительности'), ('Ненормативная лексика', 'Ненормативная лексика'), ('Другая причина', 'Другая причина')], default=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='goodsphoto',
            name='reason_for_not_publish',
            field=models.CharField(blank=True, choices=[('Нарушает правило сайта', 'Нарушает правило сайта'), ('Не соответствует действительности', 'Не соответствует действительности'), ('Ненормативная лексика', 'Ненормативная лексика'), ('Другая причина', 'Другая причина')], default=False, max_length=100, null=True),
        ),
    ]
