# Generated by Django 4.2.9 on 2024-04-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_alter_goodcategory_reason_for_not_publish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodcategory',
            name='category_slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Идентификатор категории'),
        ),
    ]
