# Generated by Django 4.2.9 on 2024-04-12 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_goodcategory_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodcategory',
            name='category_slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True, verbose_name='Идентификатор категории'),
            preserve_default=False,
        ),
    ]
