# Generated by Django 4.2.9 on 2024-04-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_alter_goodcategory_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodcategory',
            name='category_slug',
            field=models.SlugField(unique=True, verbose_name='Идентификатор категории'),
        ),
    ]
