# Generated by Django 4.2.9 on 2024-04-12 14:44

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_alter_goodcategory_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU')),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('delivery_method', models.CharField(choices=[('Почта', 'Почта'), ('Курьер', 'Курьер')], max_length=6)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='goods.carts')),
            ],
        ),
    ]
