# Generated by Django 4.2.9 on 2024-04-12 15:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0015_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cart',
        ),
        migrations.AlterField(
            model_name='orders',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=12, region='RU'),
        ),
        migrations.AddField(
            model_name='orders',
            name='cart',
            field=models.ManyToManyField(to='goods.carts'),
        ),
    ]
